### PR TITLE
try to add statically linked windows binary

### PR DESCRIPTION
**Pull request by Slach**

### CODE REVIEW

**Comment by azat** [comment]
I do want static binary for Windows, but I guess, it will not that easy...

Here are some relevant issues and documentation:
- https://github.com/indygreg/PyOxidizer/issues/353
- https://pyoxidizer.readthedocs.io/en/v0.4.0/distributing.html#windows
- https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_packaging_static_linking.html#building-statically-linked-binaries-on-windows

**Comment by azat** [comment]
@Slach any news?

**Comment by Slach** [comment]
SO SORRY,  have no time now

**Comment by azat** [comment]
@Slach there is no python requirement anymore, it is pure Rust now, so maybe it will be easier now!

**Pull request closed without merging**
