### PR TITLE
add "Seek N mins backward" and "Seek N mins forward"

### PR DESCRIPTION
**Pull request by Dolso**
Hello!

# Problem
The already existing "Seek 10 mins backward" and "Seek 10 mins forward" may not be enough, because sometimes you need to get data from query_log that was recorded several hours ago. So you have to press the same button a lot in a row, which is not very convenient

# Solution
As a solution to the problem, I propose to add 2 actions where we will shift not by 10 minutes, but by user entered value. That said, I find "Seek 10 mins backward" and "Seek 10 mins forward" useful too, because you don't always need to shift the period by a large value

# Disadvantages of the solution

- large number of actions are possible
- inconvenient Alt + T and Alt + t button combinations 
- Perhaps instead of two actions, they should have added just one "Seek N mins" where the forward or backward shift was adjusted with a sign. Or an action where we would enter the datetime of the end of the period

# Code deficiencies

I apologize in advance for my code. I know very little about Rust

- possibly bad error handling, while getting a non integer number
- maybe there is a better way to take out the duplicate code, besides the create_update_end_time_cb function

Thank you in advance!

### CODE REVIEW

**Review by azat — APPROVED** [review]
Hi Andrei, the idea LGTM and seeking specific number of minutes is very useful, though tons of bindings is questionable, but anyway I don't have better idea now, so I will merge the code as-is, and will think about better idea later.

**Comment by azat** [comment]
@Dolso I was thinking about this more, and I think at least it should accept time range (date begin, end), not number of minutes, since usually you have time frame

**Comment by Dolso** [comment]
> @Dolso I was thinking about this more, and I think at least it should accept time range (date begin, end), not number of minutes, since usually you have time frame

Ok, I can try to implement later if it's not urgent

**Comment by azat** [comment]
> Ok, I can try to implement later if it's not urgent

It is not, thank you!

**Comment by Dolso** [comment]
I made a separate pull request: https://github.com/azat/chdig/pull/42

**Pull request merged**
